GRANT SELECT ON SCHEMA CLB152269 TO CLB163341;



# =============================================================================
# BAU SQL
# =============================================================================

# BASE DO HANA DOS EQUIPAMENTOS

INSERT into "CLB152269"."TB_EQUI" ("EM","DT_VAL_DESDE","DT_VAL_ATE","INSTALACAO","EQUI_LOGICO","MATERIAL","FABRICANTE","MODELO","ANO_CONSTRUCAO")  (
 SELECT 
 SERNR EM, 
 AB VALIDO_DESDE,
 BIS VALIDO_ATE,
 ANLAGE INSTALACAO, 
 EQUNR EQUI_LOGICO,
 MATNR MATERIAL_SAP,
 HERST FABRICANTE,
 TYPBZ MODELO,
 BAUJJ ANO_CONSTRUCAO
 FROM "NEO_COR"."neo.cor.data::MODEL.TABLES.ZCT_DS_EQUIPAMENTOS"
 WHERE MATNR IN (
 LPAD('0802197',18,'0'),  GARNET NG 1E
 LPAD('0815062',18,'0'),  GARNET NG 2E
 LPAD('0802199',18,'0'),  GARNET NG 3E
 LPAD('0802168',18,'0'),  LANDIS 1E
 LPAD('0802166',18,'0'),  LANDIS 2E
 LPAD('0802167',18,'0'))  LANDIS 3E
 );

 SELECT
 SUBSTR(SERNR,9,10) EM
 ,AB EM_DT_DESDE
 ,BIS EM_DT_ATE
 ,ANLAGE INSTALACAO 
 ,SUBSTR(MATNR,12,7) EM_MATERIAL
 ,EQKTX EM_DESCRICAO
 ,HERST EM_FABRICANTE
 ,TYPBZ MODELO
 ,BAUJJ ANO_CONST
 ,EQUNR EQUI_LOG
 FROM "NEO_COR"."neo.cor.data::MODEL.TABLES.ZCT_DS_EQUIPAMENTOS" equi where AB > '2024-03-14' AND MATNR IN (
 LPAD('0802197',18,'0'),  GARNET NG 1E
 LPAD('0815062',18,'0'),  GARNET NG 2E
 LPAD('0802199',18,'0'),  GARNET NG 3E
 LPAD('0802168',18,'0'),  LANDIS 1E
 LPAD('0802166',18,'0'),  LANDIS 2E
 LPAD('0802167',18,'0'))  LANDIS 3E


# base equipamentos
 SELECT * FROM NEO_COR."neo.cor.data::MODEL.TABLES.ZCT_DS_EQUIPAMENTOS" ncdmtzde 


 DROP TABLE CLB152269.SMC_HEMERA;
CREATE COLUMN TABLE CLB152269.SMC_HEMERA (
    NET INT NOT NULL
    , CS INT NOT NULL
    , POSICAO NVARCHAR(2) NOT NULL
    , EM BIGINT NOT NULL
    , DT_ULT_LEITURA DATE NOT NULL
    , LEITURA_KWH BIGINT NOT NULL
    , STATUS_RELE NVARCHAR(45)
    , AGRUPAMENTO NVARCHAR(60)
	, DT_REF TIMESTAMP
    );
    
   ALTER TABLE CLB152269.SMC_HEMERA ADD (
    UTD AS (
    CASE WHEN SUBSTR(AGRUPAMENTO,13,3) = 'FEN' THEN 'FEIRA NORTE'
        WHEN SUBSTR(AGRUPAMENTO,13,3) = 'FES' THEN 'FEIRA SUL'
        WHEN SUBSTR(AGRUPAMENTO,13,3) = 'SAJ' THEN 'STO ANT JESUS'
        WHEN SUBSTR(AGRUPAMENTO,13,3) = 'CAM' THEN 'CAMACARI'
        WHEN SUBSTR(AGRUPAMENTO,13,3) = 'CAN' THEN 'CANDEIAS'
        WHEN SUBSTR(AGRUPAMENTO,13,3) = 'LAU' THEN 'LAURO FREITAS'
        WHEN SUBSTR(AGRUPAMENTO,13,3) = 'GRA' THEN 'GRACA'
        WHEN SUBSTR(AGRUPAMENTO,13,3) = 'ITA' THEN 'ITAPOAN'
        WHEN SUBSTR(AGRUPAMENTO,13,3) = 'PER' THEN 'PERIPERI'
        WHEN SUBSTR(AGRUPAMENTO,13,3) = 'PIR' THEN 'PIRAJA'
        WHEN SUBSTR(AGRUPAMENTO,13,3) = 'PIT' THEN 'PITUBA'
        WHEN SUBSTR(AGRUPAMENTO,13,3) = 'ILH' THEN 'ILHEUS'
        ELSE 'DESCONHECIDO' END
    )
    , SETOR AS (
        CASE 
            WHEN SUBSTR(AGRUPAMENTO, 13, 3) IN ('FEN', 'FES') THEN 'CENTRO'
            WHEN SUBSTR(AGRUPAMENTO, 13, 3) = 'SAJ' THEN 'CENTRO SUL'
            WHEN SUBSTR(AGRUPAMENTO, 13, 3) IN ('CAM', 'CAN', 'LAU') THEN 'METROPOLITANO'
            WHEN SUBSTR(AGRUPAMENTO, 13, 3) IN ('GRA', 'ITA', 'PER', 'PIR', 'PIT') THEN 'SALVADOR'
            WHEN SUBSTR(AGRUPAMENTO, 13, 3) = 'ILH' THEN 'SUL'
            ELSE 'DESCONHECIDO'
        END
    )
    , DIAS_SEM_LEITURA AS (
        DAYS_BETWEEN(DT_ULT_LEITURA,DT_REF)
    )
    , COMM_EM_D02 AS (
        CASE WHEN DAYS_BETWEEN(DT_ULT_LEITURA,DT_REF) <2 THEN 'ON' ELSE 'OFF' END
    )
);

UPDATE B 
SET  B.DT_REF = '2024-08-06 09:30:54'
FROM CLB152269.SMC_BASE_HEMERA B;

DROP VIEW "CLB152269"."VW_HEMERA";
CREATE VIEW "CLB152269"."VW_HEMERA" AS
SELECT * FROM CLB152269.SMC_HEMERA WHERE DT_REF = (SELECT MAX(DT_REF) FROM CLB152269.SMC_HEMERA)



CREATE VIEW "CLB152269"."VW_SMC" AS -- OBSOLETO!!
SELECT 
ANLAGE INSTALACAO
-- HEMERA
, NET 
, CS 
, POSICAO 
, SERNR N_SERIE_EM
, CASE WHEN EM IS NULL THEN 'S/ CAD HEMERA'
    ELSE 'OUTRO' END DEFEITO 
, LEITURA_KWH
, STATUS_RELE
, AGRUPAMENTO
, DT_REF
, UTD
, SETOR
, DIAS_SEM_LEITURA
, COMM_EM_D02
-- SAP MEDIDOR
, BIS DT_VAL_ATE_EM
, AB DT_VAL_DESDE_EM
, HERST FABRICANTE_EM
, TYPBZ MODELO_EM
, BAUJJ ANO_C_EM
, MATNR MATERIAL_EM
, EQKTX DESCRICAO_EM
-- SAP CLIENTE

FROM NEO_COR."neo.cor.data::MODEL.TABLES.ZCT_DS_EQUIPAMENTOS" equi 
LEFT JOIN CLB152269.VW_HEMERA hemera ON LPAD(hemera.EM,18,'0') = equi.SERNR
WHERE ANLAGE IN (SELECT DISTINCT zcginstal FROM CLB162419.REPETIBILIDADE_SMC_PROP)
AND BIS = '9999-12-31'
ORDER BY NET, CS, POSICAO;


-- BASE CLIENTES SMC
SELECT 
ZCGINSTAL INSTALACAO
, ZCGACCOUN CC
, ZCGSITUCC STATUS_CLIENTE
, TENSAO QTD_ELEMENTOS
, ZCGTARTYP CAT_TAR
, ZCGDSCNAE TIPO_CNAE
, BAIXARENDA
, ZCGDESCRI DESCRICAO_CAT_TAR
, ZCGNMLOGR ENDERECO
, ZCGNUMRES NUM_RESIDENCIAL
, ZCGBAIRR  BAIRRO
, ZCGPOSTO TRAFO
, ZCGPOSTE POSTE
, ZCGUNLEIT MRU
, CASE WHEN  SUBSTRING(ZCGUNLEIT, 6, 1) = 'R' THEN 'SIM'
    ELSE 'NÃO' END MRU_SMC
, ZCGOBJLIG OBJ_LIGACAO
, ZCGNOMCLI NOME_CLIENTE
, ZCGVALIDA DOCUMENTO_TIPO
, ZCGTAXNUM DOCUMENTO_VALOR
FROM CLB961851.PLANILHAO_CLIENTE pc 
WHERE SEQCC = 1
AND ZCGINSTAL IN (SELECT DISTINCT zcginstal FROM CLB162419.REPETIBILIDADE_SMC_PROP);



-- BASE VW_SMC
DROP VIEW "CLB152269"."VW_SMC";
CREATE VIEW "CLB152269"."VW_SMC" AS 
SELECT 
-- principal
cliente_smc.INSTALACAO 
, equi.N_SERIE_EM
, pc.ZCGSITUCC STATUS_CLIENTE
, CASE  WHEN equi.N_SERIE_EM IS NULL THEN 'BASE EQUI_INCOMPLETA'
    WHEN hemera.EM IS NULL THEN 'S/ CAD HEMERA'
    WHEN hemera.COMM_EM_D02 = 'ON' THEN 'SEM DEFEITO'
    ELSE 'COM DEFEITO' END DEFEITO_COMM
-- HEMERA
, hemera.NET 
, hemera.CS 
, hemera.POSICAO 
, hemera.LEITURA_KWH
, hemera.STATUS_RELE
, hemera.AGRUPAMENTO
, hemera.DT_REF
, hemera.UTD
, hemera.SETOR
, hemera.DIAS_SEM_LEITURA
, hemera.COMM_EM_D02
-- SAP CLIENTES
, pc.ZCGACCOUN CC
, pc.TENSAO QTD_ELEMENTOS
, pc.ZCGTARTYP CAT_TAR
, pc.ZCGDSCNAE TIPO_CNAE
, pc.BAIXARENDA
, pc.ZCGDESCRI DESCRICAO_CAT_TAR
, pc.ZCGNMLOGR ENDERECO
, pc.ZCGNUMRES NUM_RESIDENCIAL
, pc.ZCGBAIRR  BAIRRO
, pc.ZCGPOSTO TRAFO
, pc.ZCGPOSTE POSTE
, pc.ZCGUNLEIT MRU
, CASE WHEN  SUBSTRING(ZCGUNLEIT, 6, 1) = 'R' THEN 'SIM'
    ELSE 'NÃO' END MRU_SMC
, pc.ZCGOBJLIG OBJ_LIGACAO
, pc.ZCGNOMCLI NOME_CLIENTE
, pc.ZCGVALIDA DOCUMENTO_TIPO
, pc.ZCGTAXNUM DOCUMENTO_VALOR
-- SAP EQUIPAMENTOS
, equi.DT_VAL_ATE_EM
, equi.DT_VAL_DESDE_EM
, equi.FABRICANTE_EM
, equi.MODELO_EM
, equi.ANO_C_EM
, equi.MATERIAL_EM
, equi.DESCRICAO_EM
FROM (SELECT DISTINCT zcginstal INSTALACAO FROM CLB162419.REPETIBILIDADE_SMC_PROP) cliente_smc
LEFT JOIN (SELECT 
a.ANLAGE INSTALACAO
, b.SERNR N_SERIE_EM
, b.BIS DT_VAL_ATE_EM
, b.AB DT_VAL_DESDE_EM
, b.HERST FABRICANTE_EM
, b.TYPBZ MODELO_EM
, b.BAUJJ ANO_C_EM
, b.MATNR MATERIAL_EM
, b.EQKTX DESCRICAO_EM
FROM (SELECT ANLAGE, max(BIS) dt_ate,  MAX(AB) dt_desde FROM NEO_COR."neo.cor.data::MODEL.TABLES.ZCT_DS_EQUIPAMENTOS" GROUP BY ANLAGE) a
LEFT JOIN NEO_COR."neo.cor.data::MODEL.TABLES.ZCT_DS_EQUIPAMENTOS" b ON (b.ANLAGE = a.ANLAGE) AND (b.BIS = a.dt_ate) AND (b.AB = a.dt_desde) AND SUBSTRING(MATNR, 13, 1)  = '8') equi ON equi.INSTALACAO = cliente_smc.INSTALACAO
LEFT JOIN CLB152269.VW_HEMERA hemera ON LPAD(hemera.EM,18,'0') = equi.N_SERIE_EM
LEFT JOIN CLB961851.PLANILHAO_CLIENTE pc ON (pc.ZCGINSTAL = cliente_smc.INSTALACAO) AND (pc.SEQCC = 1)
ORDER BY net, cs, posicao;


SELECT -- ID, FK_DIR, "INPUT", INSTALACAO, NOTA, ANALISE, TITULO_EMAIL, TAG, USUARIO, DT_CRIA
TO_VARCHAR(TO_DATE(DT_CRIA),'MM/YY') REF
, COUNT(*) QTD_ANALISES
, SUM(CASE WHEN FK_DIR = 'D01' THEN 1 ELSE 0 END) "D01-ALARME"
, SUM(CASE WHEN FK_DIR = 'D02' THEN 1 ELSE 0 END) "D02-CONSUMO"
FROM CLB152269.GA_MONITOR GM
GROUP BY TO_VARCHAR(TO_DATE(DT_CRIA),'MM/YY')


-- BASE NOTAS (ANALISE LIVRE)
SELECT 
CAST(N.ZCGQMNUM AS BIGINT) NOTAS
, N.ZCGINSTAL INSTALACAO
, N.ZCGUSRSTS STATUS
, N.ZCGDTCRIA DTCRIA
, CASE WHEN N.ZCGDTFINA = '1900-01-01' THEN NULL ELSE N.ZCGDTFINA END DTFIM
, CASE WHEN N.ZCGTPNOTA <> 'CI' THEN NULL ELSE REPLACE(SUBSTRING(ZCGTXTNOT,LOCATE(ZCGTXTNOT,'_')+1,3),'#','') END DIRECIONADOR
, ZCGTXTNOT DESCRICAO_NOTA
FROM "CLB_CCS_ICC"."ZCT_DS_TAB004" N
WHERE (ZCGCREABY IN ('CLB152269','CLB162434','CLB157791','CLB153869') AND ZCGDTCRIA > '2024-01-01')
OR N.ZCGQMNUM = '004604340425'
ORDER BY ZCGDTENCE desc, ZCGDTCRIA DESC